
# LAUNCH MENU
OP_TOURNAMENT_MENU = "1"
OP_CHANGE_RANK = "2"
OP_REPORT_MENU = "3"
OP_QUIT_PROGRAM = "0"

# TOURNAMENT MENU
OP_START_TOURNAMENT = "1"
OP_CONTINUE_TOURNAMENT = "2"
OP_LAUNCH_MENU = "0"

# REPORT MENU
OP_LIST_PLAYERS_ALPHA = "1"
OP_LIST_PLAYERS_RANK = "2"
OP_LIST_TOURNAMENT = "3"
OP_LIST_PLAYER_PER_TOURNALENT_ALPHA = "4"
OP_LIST_PLAYER_PER_TOURNALENT_RANK = "5"
OP_LIST_ROUND_PER_TOURNAMENT = "6"
OP_LIST_MATCH_PER_TOURNAMENT = "7"
OP_MAIN_MENU = "0"

